# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
    push:
        paths:
            - "**.php"
    pull_request:
        paths:
            - "**.php"

name: "Code style"

jobs:
    run:
        name: "Code Style"
        runs-on: ${{ matrix.operating-system }}
        strategy:
            fail-fast: false
            matrix:
                operating-system: [ubuntu-latest]
                php-versions: ["8.1"]

        steps:
            - name: Set git to use LF
              run: |
                  git config --global core.autocrlf false
                  git config --global core.eol lf

            - name: Checkout
              uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}
                  extensions: gd,mbstring,pcov
                  tools: cs2pr

            - name: Install dependencies
              uses: ramsey/composer-install@v2

            - name: Run Grumphp
              run: vendor/bin/grumphp run --testsuite=cs -n

            - name: Send feedback on Github
              if: ${{ failure() }}
              run: |
                  vendor/bin/php-cs-fixer --allow-risky=yes --config=.php-cs-fixer.dist.php fix --dry-run --format=checkstyle | cs2pr
