name: Prettier checks

# This action works with pull requests and pushes
on:
    pull_request:
    push:

jobs:
    prettier:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

            - name: Install the Nix package manager
              uses: cachix/install-nix-action@v27

            - name: Checks
              run: nix run nixpkgs#nodePackages.prettier -- --check .
