name: Prettier checks

# This action works with pull requests and pushes
on:
    pull_request:
    push:

jobs:
    prettier:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4

            - name: Install the Nix package manager
              uses: cachix/install-nix-action@v22

            - name: Checks
              run: nix run nixpkgs#nodePackages.prettier -- --check .
