name: Prettier checks

# This action works with pull requests and pushes
on:
    pull_request:
    push:

jobs:
    prettier:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4

            - name: Install the Nix package manager
              uses: cachix/install-nix-action@v22

            - name: Checks
              run: nix run nixpkgs#nodePackages.prettier -- --check .
