name: Prettier checks

# This action works with pull requests and pushes
on:
    pull_request:
    push:

jobs:
    prettier:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4

            - name: Install the Nix package manager
              uses: cachix/install-nix-action@V28

            - name: Checks
              run: nix run nixpkgs#nodePackages.prettier -- --check .
