name: Prettier checks

# This action works with pull requests and pushes
on:
    pull_request:
    push:

jobs:
    prettier:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

            - name: Install the Nix package manager
              uses: cachix/install-nix-action@v30

            - name: Checks
              run: nix run nixpkgs#nodePackages.prettier -- --check .
