name: Prettier checks

# This action works with pull requests and pushes
on:
    pull_request:
    push:

jobs:
    prettier:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

            - name: Install the Nix package manager
              uses: cachix/install-nix-action@v27

            - name: Checks
              run: nix run nixpkgs#nodePackages.prettier -- --check .
